@startuml
salt
{
<b>Dompteur Start Page
    .
    {
        Project NEW | [Build <&beaker>] | ^HTML^ | [Show <&eye>] | --- | [ Configure <&cog> ]
        Project A | [Build <&beaker>] | ^HTML^ | [Show <&eye>] | --- | [ Configure <&cog> ]
        Project B | [Build <&beaker>] | ^PDF^ | [Show <&eye>] | --- | [ Configure <&cog> ]
        Project C | [Build <&beaker>] | ^HTML^ | [Show <&eye>] | --- | [ Configure <&cog> ]

    }
    .
    {
        [ Create new project ] | [ Import existing project ]
    }
}
@enduml