@startuml
salt
{
<b>Dompteur Start Page
    .
    {
        Project NEW | [Build <&key>] | ^HTML^ | --- | [ Configure <&key> ]
        Project A | [Build <&beaker>] | ^HTML^ | --- | [ Configure <&cog> ]
        Project B | [Build <&beaker>] | ^PDF ^ | --- | [ Configure <&cog> ]
        Project C | [Build <&beaker>] | ^HTML^ | --- | [ Configure <&cog> ]
    }
    .
    {
        [ Create new project ] | [ Import existing project ]
    }
}
@enduml